steps:
  - id: &install install-deps
    name: &npm gcr.io/cloud-builders/npm
    args:
      - ci

  - id: &build build-site
    name: *npm
    waitFor:
      - *install
    secretEnv:
      - STRAPI_API_KEY
    env:
      - 'NEXT_ADMIN_STRAPI_URL=https://admin.dentistswhoinvest.com/api'
    args: ['run', 'build']

  - id: &empty_dir create-empty-directory
    name: &gcloud gcr.io/google.com/cloudsdktool/cloud-sdk # odd to use this to run bash, but this downloads the image first. Next step timing is then realistic for how long the job took, not how long to download the image
    waitFor: ['-']
    entrypoint: bash
    args:
      - -c
      - mkdir -p ./empty

  - id: &empty_bucket empty-bucket
    name: *gcloud
    waitFor:
      - *empty_dir
    entrypoint: gcloud
    args: &empty_bucket_args
      - storage
      - rsync
      - ./empty/
      - gs://${_BUCKET}-staging
      - --recursive
      - --delete-unmatched-destination-objects

  - id: upload-html-files
    name: *gcloud
    waitFor:
      - *build
      - *empty_bucket
    entrypoint: gcloud
    args:
      - storage
      - rsync
      - ./out/
      - gs://${_BUCKET}-staging
      - --content-type=text/html
      - --exclude='.+\..*'
      - --recursive

  - id: upload-rest-of-site
    name: *gcloud
    entrypoint: gcloud
    args:
      - storage
      - rsync
      - ./out/
      - gs://${_BUCKET}-staging
      - --recursive

  - id: upload-public-assets
    name: *gcloud
    entrypoint: gcloud
    args:
      - storage
      - rsync
      - ./public/
      - gs://${_BUCKET}-staging/public/
      - --recursive

  - id: publish
    name: *gcloud
    entrypoint: gcloud
    args:
      - storage
      - rsync
      - gs://${_BUCKET}-staging/
      - gs://${_BUCKET}/
      - --recursive
      - --delete-unmatched-destination-objects

  - name: *gcloud
    id: empty-bucket-again
    entrypoint: gcloud
    args: *empty_bucket_args

options:
  logging: CLOUD_LOGGING_ONLY

# injected for each trigger, either dwi-dotcom-beta-static-assets or dwi-dotcom-static-assets
# substitutions:
  # _BUCKET: 

availableSecrets:
  secretManager:
    - versionName: projects/276123986162/secrets/STRAPI_TOKEN/versions/latest
      env: STRAPI_API_KEY
