steps:
  - name: gcr.io/cloud-builders/npm
    id: install-deps
    args:
      - ci

  - name: gcr.io/cloud-builders/npm
    id: build-site
    secretEnv:
      - STRAPI_API_KEY
    env:
      - 'NEXT_ADMIN_STRAPI_URL=https://admin.dentistswhoinvest.com/api'
    args: ['run', 'build']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: upload-entire-site
    entrypoint: gcloud
    args:
      - storage
      - rsync
      - ./out/
      - gs://${_BUCKET}-staging
      - --recursive
      - --delete-unmatched-destination-objects

  # Step 2: Upload just the files with no suffix (i.e. filenames that don’t contain a dot)
  #         with the content type explicitly set to text/html.
  #
  # The --exclude flag below uses a regex that skips any file whose path contains a dot.
  # If your directory names might contain periods, you may need to adjust the regex to apply only to
  # the file’s basename.
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: upload-html-files
    entrypoint: gcloud
    args:
      - storage
      - cp
      - ./out/
      - gs://${_BUCKET}-staging
      - --content-type=text/html
      - --exclude='.+\..*'
      - --recursive

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: upload-public-assets
    entrypoint: gcloud
    args:
      - storage
      - rsync
      - ./public/
      - gs://${_BUCKET}-staging/public/
      - --delete-unmatched-destination-objects

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: publish
    entrypoint: gcloud
    args:
      - storage
      - rsync
      - gs://${_BUCKET}-staging/
      - gs://${_BUCKET}/
      - --delete-unmatched-destination-objects
      - --recursive

options:
  logging: CLOUD_LOGGING_ONLY

# injected for each trigger, either dwi-dotcom-beta-static-assets or dwi-dotcom-static-assets
# substitutions:
  # _BUCKET: 

availableSecrets:
  secretManager:
    - versionName: projects/276123986162/secrets/STRAPI_TOKEN/versions/latest
      env: STRAPI_API_KEY
