steps:
  - name: gcr.io/cloud-builders/npm
    id: install-deps
    args:
      - ci

  - name: gcr.io/cloud-builders/npm
    id: build-site
    secretEnv:
      - STRAPI_API_KEY
    env:
      - 'NEXT_ADMIN_STRAPI_URL=https://admin.dentistswhoinvest.com/api'
    args: ['run', 'build']

  - name: gcr.io/cloud-builders/gsutil
    id: upload-site
    args: ['-m', 'rsync', '-r', '-d', './out/', 'gs://${_BUCKET}-staging']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: set-metadata
    entrypoint: bash
    args:
      - '-c'
      - >
        find out -type f ! -name "*.*" | sed 's|^out/||' | \
          xargs -I {} -P 30 gsutil setmeta -h "Content-Type:text/html" "gs://${_BUCKET}-staging/{}"

  - name: gcr.io/cloud-builders/gsutil
    id: upload-public-assets
    args: ['-m', 'rsync', '-r', '-d', './public/', 'gs://${_BUCKET}-staging/public/']

  - name: gcr.io/cloud-builders/gsutil
    id: publish
    args: ['-m', 'rsync', '-r', '-d', 'gs://${_BUCKET}-staging/', 'gs://${_BUCKET}/']

options:
  logging: CLOUD_LOGGING_ONLY

# injected for each trigger, either dwi-dotcom-beta-static-assets or dwi-dotcom-static-assets
# substitutions:
  # _BUCKET: 

availableSecrets:
  secretManager:
    - versionName: projects/276123986162/secrets/STRAPI_TOKEN/versions/latest
      env: STRAPI_API_KEY
