name: 'Build and Deploy beta to GCS'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'public/**'
      - 'src/**'
      - components.json
      - next.config.js
      - package.json
      - package-lock.json
      - postcss.config.mjs
      - tailwind.config.ts
      - tsconfig.json

env:
  PROJECT_ID: 'electric-node-426223-s2'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      - name: Setup Node.js
        uses: 'actions/setup-node@v4' # actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2' # google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/276123986162/locations/global/workloadIdentityPools/default-pool/providers/default-provider'
          service_account: "build-service@electric-node-426223-s2.iam.gserviceaccount.com"

      # todo: replace this with a build secret that can only get/list, not full permissions.
      - run: npm run debug-build
        env:
          NEXT_ADMIN_STRAPI_URL: 'https://admin.drjamesmartin.co.uk/api'
          STRAPI_API_KEY: ${{ secrets.STRAPI_API_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: 'Deploy to GCS bucket'
        run: |-
          gsutil rsync -r -d ./out/ gs://dwi-dotcom-beta-static-assets
